# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
# success_symbol = "[âœ](bold green)"
# success_symbol = "[âˆ«](bold purple)"
# success_symbol = "[ğŸŒ”Î»](bold purple)"
# success_symbol = "[â¯](bold purple)"
success_symbol = "[âœ](bold purple)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

